#!/bin/sh
# Fetch the EOT20 ocean-tide grid that build_constituents.py samples for every
# non-U.S. station, into ~/.cache/eot20/EOT20_ocean.nc (override with $EOT20_NC).
#
# This is the consolidated single-file build published with Chad Greene's Tide
# Model Driver: 27 MB, one file, already in the layout build_constituents.py
# expects (hRe/hIm as int16+scale_factor over (constituents, lat, lon), metres,
# with the constituent order on the `constituents` variable).
#
# Deliberately NOT the SEANOE original (doi:10.17882/79489). That is the
# authoritative source and is the right citation, but it ships as a 2.3 GB zip
# of 17 per-constituent files that still need joining, and the server sends no
# Accept-Ranges -- so an interrupted transfer restarts from zero. It is not
# practical to fetch over an unreliable link.
#
# Verified: with the file this script installs, 92 of the 93 shipped WORLD
# stations regenerate byte-for-byte. The one exception is Lacanau (9900093),
# which was committed as an interpolated placeholder and never came from EOT20.
set -eu

DEST="${EOT20_NC:-$HOME/.cache/eot20/EOT20_ocean.nc}"
URL="https://www.chadagreene.com/tide_data/EOT20_ocean.nc.zip"

if [ -f "$DEST" ]; then
    echo "already present: $DEST"
    exit 0
fi

mkdir -p "$(dirname "$DEST")"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "fetching $URL"
curl -fSL --retry 3 -o "$tmp/eot20.zip" "$URL"
unzip -q -o "$tmp/eot20.zip" -d "$tmp"
mv "$tmp/EOT20_ocean.nc" "$DEST"
echo "-> $DEST"

# Cheap proof the file is the one the generator expects, rather than trusting
# the download: regenerating a shipped station must not change it.
cd "$(dirname "$0")"
# Scoped to the one file, so an unrelated work-in-progress tree does not make
# this look like a failure.
if python3 build_constituents.py --only 9900033 >/dev/null 2>&1 && git diff --quiet tides/9900033.json; then
    echo "check: Newquay (9900033) regenerated byte-for-byte"
else
    echo "CHECK FAILED: regenerating a shipped station changed it -- do not trust this file" >&2
    exit 1
fi
